---
- name: add apt repos
  apt_repository: repo="{{ item }}" state=present
  with_items:
    - 'deb http://archive.ubuntu.com/ubuntu trusty main universe'
    - 'deb http://archive.ubuntu.com/ubuntu trusty-updates main universe'

- name: install java
  apt:
    name: openjdk-7-jre-headless
    update_cache: yes
    install_recommends: no

- name: create selenium user
  user: name=seluser groups=sudo

- name: make selenium directory
  file: path=/opt/selenium state=directory owner=seluser
